### ISSUE TITLE
تو تنظیمات ترمینال لینوکس نمیاد

### ISSUE THREAD

**Issue by shirejoni** [kiamazi/zira-code-font#1]
سلام و خسته نباشید من فونت رو از طریق همین کاتب نصب کردم ولی تو تنظیمات ترمینال توی فونتام پیدا نمیشه با اینکه وزیر و firacode 
خودشون هستند
توی پوشه 
~/.local/share/fonts
هم هستش

**Comment by kiamazi** [comment]
فونت رو از مسیر
`~/.local/share/fonts`
پاک کنید و مطمین بشید فقط یک نسخه از اون و تنها توی مسیر
`~/.local/share/fonts/farsifreefont`
وجود داشته باشه
‫یا اینکه نصب با دستور sudo  رو امتحان کنید
`sudo kateb install zira`

**Comment by kiamazi** [comment]
‫یکی از مشکلاتی که فونت داشت و بهش دقت نکرده بودم این بود که توی لیست فونت‌های `mono` قرار نمیگرفت، که فکر کنم الان رفع شده باشه
